# Generated by Django 4.2.16 on 2024-10-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_id',
            field=models.ImageField(upload_to='face_ids/'),
        ),
    ]
