# Generated by Django 4.2.16 on 2024-10-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_userprofile_face_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='face_id',
            field=models.ImageField(upload_to='face_id_images/'),
        ),
    ]
